verify-master-key:
  handler: src/modules/middlewares/auth.masterKey

register-list-listener:
  handler: src/modules/endpoints/listener.register
  events:
    - http:
        path: /listener
        method: post
        cors: true
        authorizer: verify-master-key

check-prices:
  handler: src/modules/endpoints/checkPrices.handler
  events:
    - http:
        path: /check-prices
        method: post
        cors: true
        authorizer: verify-master-key

create-db-structure:
  handler: src/modules/endpoints/createDbStructure.handler
  events:
    - http:
        path: /create-db-structure
        method: post
        cors: true
        authorizer: verify-master-key